language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"

# Use fast travis build infrastructure explicitly
sudo: false
dist: xenial

# Installation installs dependencies
install:
  - pip install pytz 'enum34;python_version<"3.4"' attrs .

script:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then cd tests && python -E -Wall -tt -bb test_serpent.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then cd tests && python -E -Wall -bb test_serpent.py; fi
# pypy doesn't like -tt option
